# Generated by Django 4.2.4 on 2023-08-14 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("innovar", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chavepermissao",
            name="cpf_superior",
        ),
        migrations.AddField(
            model_name="chavepermissao",
            name="atendente",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="innovar.atendente",
            ),
        ),
        migrations.AlterField(
            model_name="atendente",
            name="usuario",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Desconto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("procedimento", "Procedimento"),
                            ("pacote", "Pacote"),
                        ],
                        max_length=20,
                    ),
                ),
                ("item_id", models.PositiveIntegerField()),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("eh_porcentagem", models.BooleanField(default=False)),
                ("data_aplicacao", models.DateTimeField(auto_now_add=True)),
                (
                    "aplicado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="innovar.atendente",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="descontos",
                        to="innovar.cliente",
                    ),
                ),
            ],
        ),
    ]
