# Generated by Django 4.2.4 on 2023-08-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("innovar", "0002_remove_chavepermissao_cpf_superior_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="desconto",
            name="aplicado_por",
        ),
        migrations.RemoveField(
            model_name="desconto",
            name="eh_porcentagem",
        ),
        migrations.RemoveField(
            model_name="desconto",
            name="item_id",
        ),
        migrations.AddField(
            model_name="clientepacote",
            name="sessoes_completas",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="clientepacote",
            name="sessoes_total",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="clienteprocedimento",
            name="sessoes_total",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
