# Generated by Django 4.2.4 on 2023-08-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("innovar", "0002_remove_horariobloqueado_atendentes_cliente_cpf_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="cpf",
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="numero_telefone",
            field=models.CharField(max_length=15),
        ),
    ]
