# Generated by Django 4.2.4 on 2023-08-14 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("innovar", "0003_alter_cliente_cpf_alter_cliente_numero_telefone"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usuariocustomizado",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AlterModelManagers(
            name="usuariocustomizado",
            managers=[],
        ),
        migrations.AlterField(
            model_name="atendente",
            name="usuario",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="usuario",
            field=models.OneToOneField(
                limit_choices_to={"eh_atendente": False},
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
