# Generated by Django 4.2.4 on 2023-08-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("innovar", "0003_remove_desconto_aplicado_por_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="cpf",
            field=models.CharField(max_length=14, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="numero_telefone",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
