# Generated by Django 4.2.4 on 2023-08-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("innovar", "0005_remove_cliente_cpf_remove_cliente_numero_telefone"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="cpf",
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="numero_telefone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
