# Generated by Django 4.2.4 on 2023-08-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("innovar", "0006_cliente_cpf_cliente_numero_telefone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="cpf",
            field=models.CharField(max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="idade",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="numero_telefone",
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
