# Generated by Django 4.2.4 on 2023-08-21 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("innovar", "0007_alter_cliente_cpf_alter_cliente_idade_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cliente",
            name="usuario",
        ),
        migrations.AddField(
            model_name="usuariocustomizado",
            name="idade",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="usuariocustomizado",
            name="possui_alergia",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usuariocustomizado",
            name="possui_problema_cardiaco",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usuariocustomizado",
            name="possui_problema_fisico",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usuariocustomizado",
            name="possui_problema_respiratorio",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usuariocustomizado",
            name="prescricao_medica",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="clientepacote",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pacotes_cliente",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="clientepacote",
            name="pacote",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clientes_pacote",
                to="innovar.pacote",
            ),
        ),
        migrations.AlterField(
            model_name="clienteprocedimento",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="procedimentos_cliente",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="clienteprocedimento",
            name="procedimento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clientes_procedimento",
                to="innovar.procedimento",
            ),
        ),
        migrations.DeleteModel(
            name="Atendente",
        ),
        migrations.DeleteModel(
            name="Cliente",
        ),
    ]
