# Generated by Django 4.2.4 on 2023-08-21 17:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("innovar", "0008_remove_cliente_usuario_usuariocustomizado_idade_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuariocustomizado",
            name="eh_atendente",
        ),
        migrations.RemoveField(
            model_name="usuariocustomizado",
            name="eh_cliente",
        ),
    ]
