# Generated by Django 4.2.4 on 2023-08-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("innovar", "0009_remove_usuariocustomizado_eh_atendente_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuariocustomizado",
            name="eh_atendente",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usuariocustomizado",
            name="eh_cliente",
            field=models.BooleanField(default=False),
        ),
    ]
