# Generated by Django 4.2.4 on 2023-08-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("innovar", "0010_usuariocustomizado_eh_atendente_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientepacote",
            name="sessoes_completas",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="clientepacote",
            name="sessoes_total",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="clienteprocedimento",
            name="sessoes_total",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
