# Generated by Django 4.2.4 on 2023-08-21 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("innovar", "0011_clientepacote_sessoes_completas_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pacote",
            name="clientes",
            field=models.ManyToManyField(
                related_name="pacotes",
                through="innovar.ClientePacote",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="procedimento",
            name="clientes",
            field=models.ManyToManyField(
                related_name="procedimentos",
                through="innovar.ClienteProcedimento",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="clientepacote",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="clientepacote",
            name="pacote",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="innovar.pacote"
            ),
        ),
        migrations.AlterField(
            model_name="clientepacote",
            name="sessoes_total",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="clienteprocedimento",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="clienteprocedimento",
            name="procedimento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="innovar.procedimento"
            ),
        ),
        migrations.AlterField(
            model_name="clienteprocedimento",
            name="sessoes_total",
            field=models.PositiveIntegerField(),
        ),
    ]
