# Generated by Django 4.2.4 on 2023-08-21 18:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("innovar", "0014_alter_clientepacote_cliente_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="clientepacote",
            unique_together={("cliente", "pacote")},
        ),
        migrations.AlterUniqueTogether(
            name="clienteprocedimento",
            unique_together={("cliente", "procedimento")},
        ),
    ]
