# Generated by Django 4.2.4 on 2023-08-22 17:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("innovar", "0017_desconto_cpf_superior"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="desconto",
            name="cpf_superior",
        ),
        migrations.RemoveField(
            model_name="desconto",
            name="pacotes",
        ),
        migrations.RemoveField(
            model_name="desconto",
            name="percentual",
        ),
        migrations.RemoveField(
            model_name="desconto",
            name="procedimentos",
        ),
        migrations.RemoveField(
            model_name="desconto",
            name="valor_em_dinheiro",
        ),
        migrations.AddField(
            model_name="desconto",
            name="chave_permissao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="innovar.chavepermissao",
            ),
        ),
        migrations.AddField(
            model_name="desconto",
            name="pacote",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="innovar.pacote",
            ),
        ),
        migrations.AddField(
            model_name="desconto",
            name="percentual_desconto",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="desconto",
            name="procedimento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="innovar.procedimento",
            ),
        ),
        migrations.AddField(
            model_name="desconto",
            name="tipo_desconto",
            field=models.CharField(
                choices=[("dinheiro", "Dinheiro"), ("porcentagem", "Porcentagem")],
                default="valor",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="desconto",
            name="valor_desconto",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
