# Generated by Django 4.2.4 on 2023-08-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "innovar",
            "0018_remove_desconto_cpf_superior_remove_desconto_pacotes_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="desconto",
            name="tipo_desconto",
            field=models.CharField(
                choices=[("dinheiro", "Dinheiro"), ("porcentagem", "Porcentagem")],
                max_length=15,
            ),
        ),
    ]
