# Generated by Django 4.2.4 on 2023-08-23 17:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("innovar", "0020_alter_desconto_cliente"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Desconto",
        ),
    ]
