# Generated by Django 4.2.4 on 2023-08-28 17:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("innovar", "0022_alter_pacote_nome_alter_procedimento_nome"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChavePermissao",
        ),
    ]
