# Generated by Django 4.2.4 on 2023-08-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("innovar", "0023_delete_chavepermissao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuariocustomizado",
            name="idade",
        ),
        migrations.AddField(
            model_name="usuariocustomizado",
            name="data_nascimento",
            field=models.DateField(blank=True, null=True),
        ),
    ]
